name: Build .NET 9 class library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:

    - name: Git checkout
      uses: actions/checkout@v2

    - name: Install .NET 9
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore MultiplayerHost.sln

    - name: Build
      run: dotnet build MultiplayerHost.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test MultiplayerHost.sln --no-restore --verbosity normal
