name: Publish to NuGet

on:
  push:
    branches: [ release ]
    paths:
      - 'host/**'
      - '.github/workflows/publish.yml'
  workflow_dispatch:

jobs:  
  publish-nuget:
    runs-on: ubuntu-latest
    name: NuGet Publish
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: true

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.11.0
      with:
        versionSpec: '5.x'

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.11.0

    - name: Output version info
      run: |
        echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
        echo "NuGet Version: ${{ steps.gitversion.outputs.NuGetVersion }}"

    # Added diagnostic steps
    - name: Directory structure
      run: |
        echo "Current directory structure:"
        ls -R
        
    - name: Generate lock file
      run: |
        echo "Generating lock file..."
        dotnet restore host/Host.csproj --force --use-lock-file
        echo "Lock file status:"
        ls -la host/packages.lock.json || echo "Lock file not found"
        
    - name: Set CI build flag
      run: echo "ContinuousIntegrationBuild=true" >> $GITHUB_ENV

    - name: Restore host project
      run: |
        dotnet restore host/Host.csproj --force --use-lock-file
        # Verify lock file existence
        if [ ! -f "host/packages.lock.json" ]; then
          echo "Error: Lock file was not generated"
          exit 1
        fi

    - name: Build host project
      run: dotnet build host/Host.csproj --configuration Release --no-restore

    - name: Test host project
      run: dotnet test host/Host.csproj --configuration Release --no-build --verbosity normal

    - name: Pack host project
      run: dotnet pack host/Host.csproj --output nuget-packages --configuration Release --no-build -p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersion }}

    - name: Verify package
      run: dotnet nuget verify nuget-packages/*.nupkg

    - name: Push to NuGet
      run: |
        dotnet nuget push "nuget-packages/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate

    - name: Archive NuGet package
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: nuget-packages/*.nupkg
        retention-days: 30

